In [2]:
import numpy as np

In [3]:
data_size = 7
batch_size = 3
input_size = 2
amostra = np.random.randint(0,101,size=(data_size,input_size))

In [4]:
amostra

array([[ 95,  82],
       [  4,  89],
       [ 10,  75],
       [ 22, 100],
       [ 44,  63],
       [ 71,  44],
       [ 73,  11]], dtype=int32)

In [5]:
state = []
deslocamento = []

for indice, valor in enumerate(amostra[0:data_size-batch_size+1]):
  state.append(valor)
  for i in amostra[indice+1:indice+101]:
    #print(f'no {indice} o state {state[0]} o i {i[0]} o r {deslocamento}')
    if i[0] > state[indice][0]+5:
      deslocamento.append(1)
      break
    elif i[0] < state[indice][0]-5:
      deslocamento.append(-1)
      break

In [6]:
state

[array([95, 82], dtype=int32),
 array([ 4, 89], dtype=int32),
 array([10, 75], dtype=int32),
 array([ 22, 100], dtype=int32),
 array([44, 63], dtype=int32)]

In [7]:
deslocamento

[-1, 1, 1, 1, 1]

In [8]:
acao = [-1, 1, -1, -1, 1]
reforco = []
for indice, valor in enumerate(deslocamento):
  x = acao[indice]*deslocamento[indice]
  if x>0:
    reforco.append(1)
  elif x<0:
    reforco.append(-1)
  else: reforco.append(0)

In [9]:
reforco

[1, 1, -1, -1, 1]

In [2]:
from src import scripts

ModuleNotFoundError: No module named 'src'